import { AdminLayout } from '@backoffice/layout';

export const metadata = {
  title: 'Welcome to ecommerce-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AdminLayout>{children}</AdminLayout>
      </body>
    </html>
  );
}
