enum CartStatus {
  ACTIVE
  CHECKED_OUT
}

enum ShippingType {
  STANDARD
  EXPRESS
  SAME_DAY
}

enum PaymentMethodType {
  GCASH
  CARD
  BANK_TRANSFER
  CASH_ON_DELIVERY
}

enum OrderStatus {
  PENDING
  PAID
  SHIPPED
  COMPLETED
  CANCELLED
}

type CartItem {
  productId: ObjectId!
  quantity: Int!
  unitPrice: String
  totalPrice: String
}

type PaymentMethod {
  _id: ObjectId!
  type: PaymentMethodType!
  label: String!
  description: String
  isActive: Boolean!
}

type ShippingOption {
  _id: ObjectId!
  type: ShippingType!
  label: String!
  description: String
  fee: String!
  estimatedDays: String
}

type Cart {
  _id: ObjectId!
  items: [CartItem!]!
  subtotal: String
  tax: String
  shippingFee: String
  total: String
  status: CartStatus!
  createdAt: String!
  updatedAt: String!
}

type Order {
  _id: ObjectId!
  items: [CartItem!]!
  shippingOption: ShippingOption!
  paymentMethod: PaymentMethod!

  subtotal: String!
  tax: String!
  shippingFee: String!
  total: String!

  status: OrderStatus!
  createdAt: String!
}

input UpdateCartItemInput {
  productId: ObjectId!
  quantity: Int!
}

input CheckoutInput {
  shippingOptionId: ObjectId
  paymentMethodId: ObjectId
}

input RemoveFromCartInput {
  productId: ObjectId!
}

input UpdateOrderStatusInput {
  orderId: ObjectId!
  status: OrderStatus!
}

type Query {
  # Cart
  cart(id: ObjectId!): Cart!

  # Checkout options
  shippingOptions: [ShippingOption!]!
  paymentMethods: [PaymentMethod!]!

  # Orders
  myOrders: [Order!]!
  order(id: ObjectId!): Order
}

type Mutation {
  # Cart actions
  updateCartItem(input: UpdateCartItemInput!): Boolean

  removeFromCart(input: RemoveFromCartInput!): Boolean!
  clearCart: Cart!

  # Orders
  updateOrderStatus(input: UpdateOrderStatusInput!): Boolean

  # Checkout
  checkout(input: CheckoutInput!): Order!
}

type CartProductDetails {
  thumbnail: String!
  name: String!
  price: Decimal!
  productId: ObjectId!
}
input ProductByIdsInput {
  ids: [ObjectId!]!
}
type Query {
  productByIds(ids: ProductByIdsInput): CartProductDetails!
}
