scalar JSON
scalar ObjectId
scalar DateTime
scalar Decimal
scalar Cursor
scalar Upload

interface Node {
  _id: ObjectId!
}

type KeyValuePair {
  key: String!
  value: String!
}
type Connection {
  totalCount: Int!
  edges: [Edge!]!
  pageInfo: PageInfo!
}
type PageInfo {
  hasNextPage: Boolean!
  endCursor: Cursor
}

type Edge {
  cursor: Cursor!
  node: Node!
}
input IntFilterInput {
  equal: Int
  notEqual: Int
  in: [Int!]
  notIn: [Int!]
  lesserThan: Int
  lesserThanOrEqual: Int
  greaterThan: Int
  greaterThanOrEqual: Int
}

directive @authorizationRequired(roles: [AccountType!]!) on FIELD_DEFINITION
