enum StatusType {
  ACTIVE
  INACTIVE
  SOLD_OUT
  DRAFT
}
enum ReservationType {
  AVAILABLE
  UNAVAILABLE
}
enum CategoryType {
  FRUIT
  DAIRY
  VEGETABLES
  FISH
  SWEETS
}

interface Voucher {
  date: DateTime
  name: String
  description: String
  code: String
  value: Int
}

type Product implements Node {
  _id: ObjectId!
  thumbnail: String!
  name: String!
  price: Int!
  status: StatusType!
  discount: Int!
  points: Decimal!
  category: [CategoryType!]
  pieces: Int!
  type: CategoryType
  description: String
  reservation: ReservationType
  flashSale: Boolean
  variations: [KeyValuePair!]
  sold: Int
  vouchers: [Voucher!]
  dateAdded: DateTime
}

input ProductsStatusFilterInput {
  equal: StatusType
  in: [StatusType!]
  notIn: [StatusType!]
  notEqual: StatusType
}
input ProductsCategoryFilterInput {
  equal: CategoryType
  in: [CategoryType!]
  notIn: [CategoryType!]
  notEqual: CategoryType
}
input ProductsFilterInput {
  status: ProductsStatusFilterInput
  category: ProductsCategoryFilterInput
}
type Query {
  products(first: Int, after: Cursor, filter: ProductsFilterInput): Connection!
}
input KeyValuePairInput {
  key: String!
  value: String!
}
input VoucherInput {
  date: DateTime
  name: String
  description: String
  code: String
  value: Int
}

input CreateProductInput {
  _id: ObjectId!
  thumbnail: String!
  name: String!
  price: Int!
  status: StatusType!
  discount: Int
  points: Decimal!
  category: [CategoryType!]!
  pieces: Int!
  type: CategoryType
  description: String
  reservation: ReservationType
  flashSale: Boolean
  variations: [KeyValuePairInput!]
  sold: Int
  vouchers: [VoucherInput!]
  dateAdded: DateTime
}
input UpdateProductInput {
  _id: ObjectId!
  thumbnail: String!
  name: String!
  price: Int!
  status: StatusType!
  discount: Int
  points: Decimal!
  category: [CategoryType!]!
  pieces: Int!
  type: CategoryType
  description: String
  reservation: ReservationType
  flashSale: Boolean
  variations: [KeyValuePairInput!]
  vouchers: [VoucherInput!]
  dateAdded: DateTime
}

input DeleteProductInput {
  _id: ObjectId!
}
type Mutation {
  createProduct(input: CreateProductInput!): Boolean
  updateProduct(input: UpdateProductInput!): Boolean
  deleteProduct(input: DeleteProductInput!): Boolean
}
