fragment ProductCoreData on Product {
  _id
  name
  price
  points
  pieces
  status
  discount
  category
  thumbnail
}
query Products($first: Int, $after: Cursor, $filter: ProductsFilterInput) {
  products(first: $first, after: $after, filter: $filter) {
    pageInfo {
      hasNextPage
      endCursor
    }

    edges {
      cursor
      node {
        ...ProductCoreData
      }
    }
    totalCount
  }
}

mutation CreateProduct($input: CreateProductInput!) {
  createProduct(input: $input)
}

mutation UpdateProduct($input: UpdateProductInput!) {
  updateProduct(input: $input)
}

mutation DeleteProduct($input: DeleteProductInput!) {
  deleteProduct(input: $input)
}

query Config {
  config {
    _id
    highPointsThreshold
    topSoldThreshold
    carouselItems
  }
}
mutation CreateConfig($input: CreateConfigInput!) {
  createConfig(input: $input)
}
mutation UpdateConfig($input: UpdateConfigInput!) {
  updateConfig(input: $input)
}

query HighPointProducts(
  $first: Int
  $after: Cursor
  $filter: ProductsFilterInput
) {
  highPointProducts(first: $first, after: $after, filter: $filter) {
    pageInfo {
      hasNextPage
      endCursor
    }

    edges {
      cursor
      node {
        ...ProductCoreData
      }
    }
    totalCount
  }
}
