mutation CreateMemberAccount($input: CreateAccountInput!) {
  createMemberAccount(input: $input)
}
mutation CreateAdminAccount($input: CreateAccountInput!) {
  createAdminAccount(input: $input)
}

query Self {
  self {
    _id
    emailAddress
    role
  }
}
