mutation UpdateCartItem($input: UpdateCartItemInput!) {
  updateCartItem(input: $input)
}

query Cart($id: ObjectID!) {
  cart(id: $id) {
    _id
    items {
      productId
      quantity
      unitPrice
      totalPrice
    }
    subtotal
    tax
    status
    createdAt
    updatedAt
  }
}
query MyOrders {
  myOrders {
    _id
    items {
      productId
      quantity
      unitPrice
      totalPrice
    }
    shippingOption {
      type
      label
      description
      estimatedDays
      fee
    }
    subtotal
    tax
    shippingFee
    total
    status
    createdAt
  }
}

query ShippingOptions {
  shippingOptions {
    _id
    type
    label
    description
    fee
    estimatedDays
  }
}

mutation Checkout($input: CheckoutInput!) {
  checkout(input: $input) {
    _id
    items {
      productId
      quantity
      unitPrice
      totalPrice
    }
    shippingOption {
      type
      label
      description
      estimatedDays
      fee
    }
    paymentMethod {
      type
    }
    subtotal
    tax
    shippingFee
    total
    status
    createdAt
  }
}

mutation RemoveFromCart($input: RemoveFromCartInput!) {
  removeFromCart(input: $input)
}

mutation UpdateOrderStatus($input: UpdateOrderStatusInput!) {
  updateOrderStatus(input: $input)
}
