import { AuthProvider } from '@portal/auth';
import { Provider } from '@portal/theme';
import './globals.css';

export const metadata = {
  title: 'Welcome to ecommerce-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">
        <AuthProvider>
          <Provider> {children}</Provider>
        </AuthProvider>
      </body>
    </html>
  );
}
