import { AuthProvider } from '@portal/auth';
import { Provider } from '@portal/theme';
import { Roboto } from 'next/font/google';

export const metadata = {
  title: 'Welcome to ecommerce-app',
  description: 'Generated by create-nx-workspace',
};
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className={roboto.className}>
      <body>
        <AuthProvider>
          <Provider>{children}</Provider>
        </AuthProvider>
      </body>
    </html>
  );
}
