fragment ProductCoreData on Product {
  _id
  name
  price
  points
  pieces
  status
  discount
  category
}
query Products($filter: ProductsFilterInput) {
  products(filter: $filter) {
    ...ProductCoreData
  }
}

mutation CreateProduct($input: CreateProductInput!) {
  createProduct(input: $input)
}
