fragment ProductCoreData on Product {
  _id
  name
  price
  points
  pieces
  status
  discount
  category
}
query Products {
  products {
    ...ProductCoreData
  }
}

mutation CreateProduct($input: CreateProductInput!) {
  createProduct(input: $input)
}
