fragment ProductCoreData on Product {
  _id
  name
  price
  points
  pieces
  status
  discount
  category
  thumbnail
}
query Products($filter: ProductsFilterInput) {
  products(filter: $filter) {
    pageInfo {
      hasNextPage
      endCursor
    }

    edges {
      cursor
      node {
        ...ProductCoreData
      }
    }
    totalCount
  }
}

mutation CreateProduct($input: CreateProductInput!) {
  createProduct(input: $input)
}
